export const ActionsTypes = {
    SET_CHATS: 'SET_CHATS',
    SET_SELECTED_CHAT: 'SET_SELECTED_CHAT',
    REMOVE_SELECTED_CHAT: 'REMOVE_SELECTED_CHAT'
}

export const SnackbarActionTypes = {
    OPEN_SNACKBAR: 'OPEN_SNACKBAR',
    CLOSE_SNACKBAR: 'CLOSE_SNACKBAR'
}